# Kubernetes Version
versions:
  kubernetes: v1.32.0
  talos: v1.9.0
  cpi: v1.32.1
  cni: 1.17.0-rc.0

# Control Plane Configuration
controlPlane:
  endpointIP: 192.168.0.1
  endpointPort: 6443
  replicas: 3

# Worker Machine Configuration
workers:
  replicas: 1
  autoscaler:
    enabled: true
    size:
      min: 1
      max: 5

# vSphere Configuration
vsphere:
  server: "your-vsphere-server"
  tlsThumbprint: "YOUR_TLS_THUMBPRINT"
  datacenter: "datacenter-name"
  datastore: "datastore-name"
  folder: "folder-name"
  network: "network-name"
  networkPublic: "network-public-name"
  resourcePool: ""
  storagePolicy: ""
  template: talos-v1.9