apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
    ciliumCNI: enabled
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereCluster
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
