apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  {{- if .Values.autoscaler.enabled }}
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: {{ .Values.autoscaler.size.max | quote }}
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: {{ .Values.autoscaler.size.min | quote }}
  {{- end }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name | quote }}
  name: "{{ .Values.cluster.name }}-md-0"
  namespace: {{ .Values.namespace | quote }}
spec:
  clusterName: {{ .Values.cluster.name | quote }}
  {{- if not .Values.autoscaler.enabled }}
  replicas: {{ .Values.worker.machineCount }}
  {{- end }}
  selector:
    matchLabels: {}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name | quote }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: "{{ .Values.cluster.name }}-md-0"
      clusterName: {{ .Values.cluster.name | quote }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        name: "{{ .Values.cluster.name }}-worker-{{ .Values.kubernetesVersion }}"
      version: {{ .Values.kubernetesVersion | quote }}