apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  {{- if .Values.workers.autoscaler.enable }}
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: {{ quote .Values.workers.autoscaler.size.max }}
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: {{ quote .Values.workers.autoscaler.size.min }}
  {{- end }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
  name: {{ .Release.Name }}-md-0
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Release.Name }}
  {{- if not .Values.workers.autoscaler.enabled }}
  replicas: {{ .replicas }}
  {{- end }}
  selector:
    matchLabels: {}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: {{ .Release.Name }}-{{ toJson .Values | sha256sum }}
          namespace: {{ .Release.Namespace }}
      clusterName: {{ .Release.Name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        name: {{ .Release.Name }}-worker-{{ toJson .Values | sha256sum }}
        namespace: {{ .Release.Namespace }}
      version: {{ quote .Values.versions.kubernetes }}