apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name | quote }}
  namespace: {{ .Values.namespace | quote }}
stringData:
  username: {{ .Values.vsphere.username | quote }}
  password: {{ .Values.vsphere.password | quote }}