apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneConfig:
    controlplane:
      configPatches:
      - op: add
        path: /machine/network
        value:
          interfaces:
          - dhcp: true
            interface: eth0
            vip:
              ip: {{ quote .Values.controlPlane.endpointIP }}
          - dhcp: false
            interface: eth1
      - op: add
        path: /cluster/externalCloudProvider
        value:
          enabled: true
      - op: add
          path: /machine/kubelet/extraArgs
          value:
            rotate-server-certificates: true
      - op: add
        path: /machine/install
        value:
          extraKernelArgs:
          - net.ifnames=0
      - op: add
        path: /cluster/network/cni
        value:
          name: none
      - op: add
        path: /cluster/proxy
        value:
          disabled: true
      - op: replace
        path: /cluster/controlPlane
        value:
          endpoint: "https://{{ .Values.controlPlane.endpointIP }}:{{ .Values.controlPlane.endpointPort }}"
      - op: add
        path: /machine/certSANs
        value:
        -  {{ quote .Values.controlPlane.endpointIP }}
      generateType: controlplane
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereMachineTemplate
    name: {{ .Release.Name }}-{{ toJson .Values | sha256sum }}
  replicas: {{ .Values.controlPlane.replicas }}
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  version: {{ .Values.versions.kubernetes }}
