apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: {{ .Release.Name }}-{{ toJson .Values | sha256sum }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      configPatches:
      - op: add
        path: /machine/network
        value:
          interfaces:
          - dhcp: true
            interface: eth0
          - dhcp: false
            interface: eth1
      - op: add
        path: /cluster/externalCloudProvider
        value:
          enabled: true
      - op: add
          path: /machine/kubelet/extraArgs
          value:
            rotate-server-certificates: true
      - op: add
        path: /machine/install
        value:
          extraKernelArgs:
          - net.ifnames=0
      - op: add
        path: /cluster/proxy
        value:
          disabled: true
      - op: add
        path: /cluster/discovery
        value:
          enabled: true
      - op: replace
        path: /cluster/controlPlane
        value:
          endpoint: "https://{{ .Values.controlPlane.endpointIP }}:{{ .Values.controlPlane.endpointPort }}"
      - op: add
        path: /machine/certSANs
        value:
        - {{ quote .Values.controlPlane.endpointIP }}
      generateType: worker