apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereCluster
metadata:
  name: {{ .Values.cluster.name | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  controlPlaneEndpoint:
    host: {{ .Values.controlPlaneEndpointIP | quote }}
    port: {{ .Values.controlPlaneEndpointPort }}
  identityRef:
    kind: Secret
    name: {{ .Values.cluster.name | quote }}
  server: {{ .Values.vsphere.server | quote }}
  thumbprint: {{ .Values.vsphere.tlsThumbprint | quote }}
