apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneEndpoint:
    host: {{ quote .Values.controlPlane.endpointIP }}
    port: {{ .Values.controlPlane.endpointPort }}
  identityRef:
    kind: Secret
    name: {{ .Release.Name }}
  server: {{ quote .Values.vsphere.server }}
  thumbprint: {{ quote .Values.vsphere.tlsThumbprint }}
