apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: "{{ .Values.cluster.name }}-{{ .Values.kubernetesVersion }}"
  namespace: {{ .Values.namespace | quote }}
spec:
  template:
    spec:
      cloneMode: linkedClone
      customVMXKeys:
        disk.EnableUUID: "true"
      datacenter: {{ .Values.vsphere.datacenter | quote }}
      datastore: {{ .Values.vsphere.datastore | quote }}
      diskGiB: {{ .Values.controlPlane.diskGB }}
      folder: {{ .Values.vsphere.folder | quote }}
      memoryMiB: {{ .Values.controlPlane.memoryMB }}
      network:
        devices:
        - dhcp4: true
          networkName: {{ .Values.vsphere.network | quote }}
      numCPUs: {{ .Values.controlPlane.cpuNum }}
      os: Linux
      powerOffMode: trySoft
      resourcePool: {{ .Values.vsphere.resourcePool | quote }}
      server: {{ .Values.vsphere.server | quote }}
      storagePolicyName: {{ .Values.vsphere.storagePolicy | quote }}
      template: {{ .Values.vsphere.template | quote }}
      thumbprint: {{ .Values.vsphere.tlsThumbprint | quote }}
